# Common options
common:
  email:    'exmaple@mail.com'

# sms-server settings
sms-server:
  protocol: 'http'
  host:     'localhost'
  port:     '9292'
  path:     '/enqueue'
  username: 'scc'
  password: 'admin'


# sms-client settings
sms-client:


# IRC options
irc:
  nick:     ''
  server:   ''
  channels: ['#channel']
