# Copy this file to ~/.sms and rename to config.yml

# sms-server settings
## Contact settings
contact:
  email: some-email@suse.de

## IRC settings
irc:
  nick:     'sms'
  server:   'irc.host.de'
  channels: ['#sms']

# sms-client settings
## sms-server location
sms-server:
  url:  'http://localhost:9292/enqueue'
  username: 'user'
  password: 'password'

