# Copy this file to ~/.sms and rename to config.yml

### SMS server/client options
sms-server:
  protocol: 'http'
  host:     'localhost'
  port:     '9292'
  path:     '/enqueue'
  username: 'user'
  password: 'password'

### SMS server options
# IRC options
irc:
  nick:     "sms"
  server:   "irc.example.com"
  channels: ["#channel"]

# Other options
contact:
  email: example@email.com
