---
environment: production
chdir: /path/to/sms-server/
rackup: /path/to/sms-server/config.ru
pid: /path/to/sms-server/tmp/pids/thin.pid
log: /path/to/sms-server/log/production.log
address: 127.0.0.1
port: 9292
user: user
group: group
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
