---
environment: production
chdir: .
rackup: config.ru
pid: tmp/pids/thin.pid
log: log/production.log
address: 0.0.0.0
port: 9292
max_conns: 1024
max_persistent_conns: 512
timeout: 30
daemonize: true
